In [2]:
import numpy as np
import pandas as pd

### 1 - Esercizi sugli array

1 - Creare un array v1 con valori 0 e lunghezza 10

In [82]:
v1 = np.repeat(0,10)
v1

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

2 - Creare un vettore di numeri casuali 0,1 di lunghezza 10

In [83]:
v2 = np.random.choice([0,1],10)
v2

array([1, 0, 0, 1, 1, 0, 1, 1, 1, 1])

3 - Trasformare v2 in booleano

In [84]:
v3 = v2.astype('bool')
v3

array([ True, False, False,  True,  True, False,  True,  True,  True,
        True])

4 - Quali valori di v3 sono "True"?

In [85]:
np.where(v3==True)

(array([0, 3, 4, 6, 7, 8, 9], dtype=int64),)

5 -Selezionare tutti i valori "False"

In [86]:
v3[np.where(v3==False)]

array([False, False, False])

### 2 - Array categorici

1 - Creare un vettore che contenga i termini "adulto", "bambino", "anziano" scelti casualmente e renderlo categorico

In [94]:
v4 = np.random.choice(["adulto","bambino","anziano"], 10)


In [95]:
v4 = pd.Categorical(v4)

2 - Quali sono le categorie?

In [96]:
v4.categories

Index(['adulto', 'anziano', 'bambino'], dtype='object')

3 - Riordinare le categorie

In [97]:
v4 =  v4.reorder_categories(["bambino", "adulto", "anziano"], ordered = True)
v4 = v4.sort_values()
v4

['bambino', 'bambino', 'bambino', 'adulto', 'adulto', 'adulto', 'anziano', 'anziano', 'anziano', 'anziano']
Categories (3, object): ['bambino' < 'adulto' < 'anziano']

4 - Rinominare le categorie

In [98]:
v4 = v4.rename_categories(["Bambino","Adulto","Anziano"])

In [99]:
v4.categories

Index(['Bambino', 'Adulto', 'Anziano'], dtype='object')

5 - Creare un nuovo array categorico che contenga anche due elementi ["Neonato", "Neonato"] ed riordinare gli elementi dal più giovane al più anziano

In [100]:
v5 = pd.Categorical(np.append(np.array(v4), np.array(["Neonato","Neonato"])))

In [101]:
v5 = v5.reorder_categories(["Neonato", "Bambino", "Adulto", "Anziano"], ordered = True)
v5 = v5.sort_values()
v5

['Neonato', 'Neonato', 'Bambino', 'Bambino', 'Bambino', ..., 'Adulto', 'Anziano', 'Anziano', 'Anziano', 'Anziano']
Length: 12
Categories (4, object): ['Neonato' < 'Bambino' < 'Adulto' < 'Anziano']

6 - Stampare le frequenze delle diverse categorie

In [102]:
v5.describe()

counts     freqs
categories                  
Neonato          2  0.166667
Bambino          3  0.250000
Adulto           3  0.250000
Anziano          4  0.333333

### 3 -  Valori NaN (Not a Number) 

1 - Creare un array di dimensione 10 costituito da nan

In [24]:
v6 = np.repeat(np.nan, 10)
v6

array([nan, nan, nan, nan, nan, nan, nan, nan, nan, nan])

2 - Sostituire i valori con posizione [3,4,5,9] con i valori 1,2,3,4

In [26]:
v6[[2,3,4,8]] = np.array([1,2,3,4])
v6

array([nan, nan,  1.,  2.,  3., nan, nan, nan,  4., nan])

3 - Aggiungere 5 valori casuali [Nan, 42] alla coda di v6 e contare quanti Nan ci sono

In [28]:
randomvalues = np.random.choice([np.nan, 42], 5)
randomvalues

array([42., nan, 42., nan, 42.])

In [29]:
v6 = np.append(v6, randomvalues)
v6

array([nan, nan,  1.,  2.,  3., nan, nan, nan,  4., nan, 42., nan, 42.,
       nan, 42.])

In [30]:
np.isnan(v6).sum()

8

In [32]:
len(np.where(np.isnan(v6)==True)[0])

8

4 - Sostituire i valori mancanti con il numero 10

In [33]:
v6[np.isnan(v6)] = 10
v6

array([10., 10.,  1.,  2.,  3., 10., 10., 10.,  4., 10., 42., 10., 42.,
       10., 42.])

### 4 - Liste

1 - Creare una lista l1 con i seguenti elementi h, e, 1, 1, 0

In [108]:
l1 = list(["h", "e", 1, 1, 0])
l1

['h', 'e', 1, 1, 0]

2 - Trovare gli elementi in posizione 0, 2 e 3 e l'ultimo elemento

In [109]:
[l1[i] for i in (0,2,3)]

['h', 1, 1]

In [110]:
l1[-1]

0

3 - Creare una lista l2 che contenga
- un vettore di numeri [1,2,3,4,5]
- un vettore categorico ["bambino", "adulto", "anziano"]
- un vettore booleano [True, False, True]
- una lista composta dai seguenti elementi [1, "3", True]


In [116]:
c1 = np.array([1,2,3,4,5])
c2 = pd.Categorical(["bambino", "adulto", "anziano"])
c3 = np.array([True, False, False])
c4 = list([1, "3", True])
l2 = [c1, c2, c3, c4]
l2

[array([1, 2, 3, 4, 5]),
 ['bambino', 'adulto', 'anziano']
 Categories (3, object): ['adulto', 'anziano', 'bambino'],
 array([ True, False, False]),
 [1, '3', True]]

### 5 - Esercizi sulle matrici - 1

1 - Creare una matrice m1 vuota con 7 righe e 5 colonne

In [105]:
m1 = np.round(np.empty((7,5)),0)
m1

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

2 - Stampare le dimensioni e il numero di valori nella matrice

In [106]:
m1.shape

(7, 5)

In [107]:
m1.size

35

3- Modi diversi di creare una matrici

In [6]:
m2 = np.matrix("1,0,0;0,2,0;0,0,3")
m2

matrix([[1, 0, 0],
        [0, 2, 0],
        [0, 0, 3]])

In [7]:
m3 = np.matrix([1,2,1,2,1,2]).reshape((2,3))
m3

matrix([[1, 2, 1],
        [2, 1, 2]])

In [8]:
m3 = np.array([4,2,0,0,2,4]).reshape((3,2))
m3

array([[4, 2],
       [0, 0],
       [2, 4]])

In [11]:
m3.shape[1]

2

### 6 - Operazioni varie sulle matrici

1 - Creare un matrice di valori 0 di 5 righe e 3 colonne 

In [46]:
m4 = np.repeat(0,15).reshape((5,3))
m4

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

altro modo di fare lo stess

In [117]:
m5 = np.zeros((5,3))
m5

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

2 - Creare una matrice di dimensioni 4x4 composta da questi valori [21,30,36,17,45,12,14,31,15,50,
      22,29,22,33,13,40] e calcolarne il quadrato

In [118]:
m7 = np.array([21,30,36,17,45,12,14,31,15,50,
      22,29,22,33,13,40]).reshape((4,4))
m7

array([[21, 30, 36, 17],
       [45, 12, 14, 31],
       [15, 50, 22, 29],
       [22, 33, 13, 40]])

In [119]:
np.power(m7,2)

array([[ 441,  900, 1296,  289],
       [2025,  144,  196,  961],
       [ 225, 2500,  484,  841],
       [ 484, 1089,  169, 1600]], dtype=int32)

3 - Estrarre i valori [14, 22,13] dalla matrice m7

In [25]:
m7[1:,2]

array([14, 22, 13])

4 - Ottenere l'ultima riga di m7

In [26]:
m7[-1,:]

array([22, 33, 13, 40])

5 - Aggiungere a m7 una riga con valori 0 e aggiungere una nuova colonna con valori 1

In [21]:
import pandas as pd

In [27]:
num_col = len(m7[:,1])
num_col

4

In [28]:
m7.shape

(4, 4)

In [29]:
m7.shape[1]

4

In [13]:
new_column = np.ones((1, m7.shape[1])).T
new_column

array([[1.],
       [1.],
       [1.],
       [1.]])

In [14]:
m7 = np.hstack((m7,new_column))

In [15]:
m7

array([[21., 30., 36., 17.,  1.],
       [45., 12., 14., 31.,  1.],
       [15., 50., 22., 29.,  1.],
       [22., 33., 13., 40.,  1.]])

In [16]:
new_row = np.zeros((1, m7.shape[0]+1))
new_row

array([[0., 0., 0., 0., 0.]])

In [17]:
m7 = np.vstack((m7, new_row))
m7

array([[21., 30., 36., 17.,  1.],
       [45., 12., 14., 31.,  1.],
       [15., 50., 22., 29.,  1.],
       [22., 33., 13., 40.,  1.],
       [ 0.,  0.,  0.,  0.,  0.]])

### 7 - Creazione di dataframe con diversi tipi di valori

1 - Creare un dataframe con tre colonne 
- name: ["Monica", "Alberto","Bruno", "Ilaria", "Antonio"]
- age: [10,20,5,36,80]
- category: ["bambino","adulto", "bambino","adulto","anziano"]

In [121]:
name = np.array(["Monica", "Alberto","Bruno", "Ilaria", "Antonio"])
age = np.array([10,20,5,36,80])
category = pd.Categorical(["bambino","adulto", "bambino","adulto","anziano"])
category = category.reorder_categories(["bambino", "adulto","anziano"], ordered = True)
data = {"name": name, "age": age, "category": category}
df1 = pd.DataFrame(data)
df1

name  age category
0   Monica   10  bambino
1  Alberto   20   adulto
2    Bruno    5  bambino
3   Ilaria   36   adulto
4  Antonio   80  anziano

2 - Aggiungere la colonna "gender"

In [122]:

df1["gender"] = pd.Categorical(["F","M","M","F","M"])

In [123]:
df1

name  age category gender
0   Monica   10  bambino      F
1  Alberto   20   adulto      M
2    Bruno    5  bambino      M
3   Ilaria   36   adulto      F
4  Antonio   80  anziano      M

3 - Aggiungere una nuova persona, di nome Francesco e anni 55 (adulto)

In [124]:
df1 = df1.append({"name": "Francesco", "age": 55, "category": "adulto", "gender": "M"}, ignore_index = True)

In [125]:
df1

name  age category gender
0     Monica   10  bambino      F
1    Alberto   20   adulto      M
2      Bruno    5  bambino      M
3     Ilaria   36   adulto      F
4    Antonio   80  anziano      M
5  Francesco   55   adulto      M

### 8 -  DataFrame 

1 - Caricare un file excel o csv come dataframe e verificare che è proprio un dataframe

In [4]:
import pandas as pd
#df2 = pd.read_csv("nome file")
df2 = pd.read_excel("dati_indici_20211103.xlsx")

In [5]:
type(df2)

pandas.core.frame.DataFrame

In [6]:
df2.head()

DATA  JPCAEU3M  LG13TREH  LBEATREU  LEGATREH    NDDUWI  MXWOHEUR  \
0 1999-01-31  0.002894  0.000000  0.013556  0.014568  0.060804  0.033060   
1 1999-02-28  0.002295  0.005009 -0.011451 -0.014557  0.003298 -0.014425   
2 1999-03-31  0.003112 -0.001575  0.006580  0.006532  0.061535  0.044016   
3 1999-04-30  0.003203  0.005897  0.010771  0.006090  0.061479  0.043849   
4 1999-05-31  0.002236  0.004197 -0.005647 -0.007740 -0.024039 -0.030806   

    NDUEEGF    NCUDWI  
0  0.027897  0.039463  
1  0.040799 -0.014921  
2  0.153928  0.058550  
3  0.147651  0.100637  
4  0.007252  0.001808

In [7]:
df2.tail()

DATA  JPCAEU3M  LG13TREH  LBEATREU  LEGATREH    NDDUWI  MXWOHEUR  \
267 2021-04-30 -0.000959  0.000062 -0.007070  0.001946  0.022437  0.039087   
268 2021-05-31 -0.000447  0.000185 -0.000782  0.001607 -0.002269  0.009862   
269 2021-06-30 -0.000419 -0.000984  0.003915  0.004428  0.047367  0.023412   
270 2021-07-31 -0.000442  0.001109  0.015628  0.011809  0.017055  0.016629   
271 2021-08-31 -0.000486 -0.000492 -0.004707 -0.002604  0.029402  0.026263   

      NDUEEGF    NCUDWI  
267  0.001293  0.014886  
268  0.006371 -0.008122  
269  0.033765  0.034136  
270 -0.068086 -0.007632  
271  0.030696  0.028818

2 - Verificare le caratteristiche del DF e un po' di statistiche

In [8]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 272 entries, 0 to 271
Data columns (total 9 columns):
 #   Column    Non-Null Count  Dtype         
---  ------    --------------  -----         
 0   DATA      272 non-null    datetime64[ns]
 1   JPCAEU3M  272 non-null    float64       
 2   LG13TREH  272 non-null    float64       
 3   LBEATREU  272 non-null    float64       
 4   LEGATREH  272 non-null    float64       
 5   NDDUWI    272 non-null    float64       
 6   MXWOHEUR  272 non-null    float64       
 7   NDUEEGF   272 non-null    float64       
 8   NCUDWI    272 non-null    float64       
dtypes: datetime64[ns](1), float64(8)
memory usage: 19.2 KB


In [129]:
df2.describe()

JPCAEU3M    LG13TREH    LBEATREU    LEGATREH      NDDUWI    MXWOHEUR  \
count  272.000000  272.000000  272.000000  272.000000  272.000000  272.000000   
mean     0.001483    0.001929    0.003458    0.003189    0.006093    0.005320   
std      0.001596    0.002853    0.009625    0.008036    0.041800    0.040989   
min     -0.000959   -0.004003   -0.033915   -0.020175   -0.129970   -0.178195   
25%      0.000023   -0.000015   -0.003863   -0.001976   -0.014628   -0.015516   
50%      0.001464    0.001216    0.004586    0.003574    0.010481    0.011628   
75%      0.002692    0.003656    0.009845    0.008900    0.030576    0.030093   
max      0.006043    0.012231    0.031557    0.028448    0.113863    0.117260   

          NDUEEGF      NCUDWI  
count  272.000000  272.000000  
mean     0.009026    0.009215  
std      0.056998    0.049086  
min     -0.197135   -0.205623  
25%     -0.022476   -0.015728  
50%      0.012272    0.010595  
75%      0.040949    0.040814  
max      0.168173    0.167071

3 - Verificare le dimensioni di df2 e i nomi delle colonne

In [9]:
df2.shape

(272, 9)

In [10]:
df2.columns

Index(['DATA', 'JPCAEU3M', 'LG13TREH', 'LBEATREU', 'LEGATREH', 'NDDUWI',
       'MXWOHEUR', 'NDUEEGF', 'NCUDWI'],
      dtype='object')

4 - Verificare se ci sono dati mancanti

In [11]:
df2.isnull().sum()

DATA        0
JPCAEU3M    0
LG13TREH    0
LBEATREU    0
LEGATREH    0
NDDUWI      0
MXWOHEUR    0
NDUEEGF     0
NCUDWI      0
dtype: int64

### 9 - Gestire i valori mancanti di un DF

Carichiamo lo stesso Df dell'esercizio precedente nel quale abbiamo creato campi vuoti

In [12]:
df3 = pd.read_excel("dati_indici_20211103_na.xlsx")

In [13]:
type(df3)

pandas.core.frame.DataFrame

verifichiamo se e quanti valori mancanti ci sono in ciascuna colonna di df3

In [17]:
df3.isnull().sum()

DATA        0
JPCAEU3M    5
LG13TREH    1
LBEATREU    4
LEGATREH    1
NDDUWI      2
MXWOHEUR    4
NDUEEGF     0
NCUDWI      2
dtype: int64

1 - Sostituire i valori mancanti (NaN) della colonna 1 (JPCAEU3M) con la media dei valori della stessa colonna

In [136]:
val_not_nan = df3[df3['JPCAEU3M'].notnull()]
len(val_not_nan)

267

In [137]:
a = np.average(val_not_nan['JPCAEU3M'])
a

0.001471427194232164

In [138]:
df3['JPCAEU3M'] = df3['JPCAEU3M'].fillna(np.average(val_not_nan['JPCAEU3M']))
df3['JPCAEU3M']

0      0.002894
1      0.002295
2      0.003112
3      0.003203
4      0.002236
         ...   
267   -0.000959
268   -0.000447
269   -0.000419
270   -0.000442
271   -0.000486
Name: JPCAEU3M, Length: 272, dtype: float64

In [18]:
df3.isnull().sum()

DATA        0
JPCAEU3M    5
LG13TREH    1
LBEATREU    4
LEGATREH    1
NDDUWI      2
MXWOHEUR    4
NDUEEGF     0
NCUDWI      2
dtype: int64

In [19]:
type(df3)

pandas.core.frame.DataFrame

In [20]:
df3

DATA  JPCAEU3M  LG13TREH  LBEATREU  LEGATREH    NDDUWI  MXWOHEUR  \
0   1999-01-31  0.002894  0.000000  0.013556  0.014568  0.060804  0.033060   
1   1999-02-28  0.002295  0.005009 -0.011451 -0.014557  0.003298 -0.014425   
2   1999-03-31  0.003112 -0.001575  0.006580  0.006532  0.061535  0.044016   
3   1999-04-30  0.003203  0.005897  0.010771  0.006090  0.061479  0.043849   
4   1999-05-31  0.002236  0.004197 -0.005647 -0.007740 -0.024039 -0.030806   
..         ...       ...       ...       ...       ...       ...       ...   
267 2021-04-30 -0.000959  0.000062 -0.007070  0.001946  0.022437  0.039087   
268 2021-05-31 -0.000447  0.000185 -0.000782  0.001607 -0.002269  0.009862   
269 2021-06-30 -0.000419 -0.000984  0.003915  0.004428  0.047367  0.023412   
270 2021-07-31 -0.000442  0.001109  0.015628  0.011809  0.017055       NaN   
271 2021-08-31 -0.000486 -0.000492 -0.004707 -0.002604  0.029402  0.026263   

      NDUEEGF    NCUDWI  
0    0.027897  0.039463  
1    0.040799 -0.014921  
2    0.153928  0.058550  
3    0.147651  0.100637  
4    0.007252  0.001808  
..        ...       ...  
267  0.001293  0.014886  
268  0.006371 -0.008122  
269  0.033765  0.034136  
270 -0.068086 -0.007632  
271  0.030696  0.028818  

[272 rows x 9 columns]

2 - Eliminare tutte le righe dove ci sono valori mancanti

In [142]:
df3.dropna(inplace=True)

3 - Verificare quanti sono i valori mancanti in  ciascuna colonna

In [143]:
df3.isnull().sum()

DATA        0
JPCAEU3M    0
LG13TREH    0
LBEATREU    0
LEGATREH    0
NDDUWI      0
MXWOHEUR    0
NDUEEGF     0
NCUDWI      0
dtype: int64

4 - Verificare quanti valori mancanti ci sono in df3

In [144]:
df3.isnull().sum().sum()

0