### Assegnazione di variabili e nomi

In [ ]:
x = 3
x

3

In [ ]:
x = x + 1
x

4

In [ ]:
z = "hello BISF"
z

'hello BISF'

In [ ]:
y = a

NameError: name 'a' is not defined

In [ ]:
y = "a"
y

'a'

In [ ]:
m = "b"
m

'b'

In [ ]:
n = y + m
n

'ab'

Molte funzioni non sono nella libreria base di Python

In [ ]:
Z = sqrt(2)
Z

NameError: name 'sqrt' is not defined

In [ ]:
# occorre perciò importare la libreria che la contiene
import math

In [ ]:
Z = math.sqrt(2)
Z

1.4142135623730951

Questo modo di assegnare lo stesso valore a più varibili non funziona

In [ ]:
a, b, c = 10

TypeError: cannot unpack non-iterable int object

Questo sì

In [ ]:
a = b = c = 10
a

10

In [ ]:
b

10

### Oggetti

#### Tuple

Le tuple sono insiemi di dati creati con una lista delimitata da parentesi tonde

In [ ]:
a = (1,2,3,4,5)
print(a)
print(type(a))

(1, 2, 3, 4, 5)
<class 'tuple'>


Le tuple sono immutabili, non si può assegnare un valore diverso a un elemento

In [ ]:
a[1] = 3

TypeError: 'tuple' object does not support item assignment

#### List

Una lista è un insieme di dati delimitati da partentesi quadre

In [ ]:
b = [1,2,3,4,5]
print(b)
print(type(b))

[1, 2, 3, 4, 5]
<class 'list'>


In [ ]:
b[1] = 3
print(b)

[1, 3, 3, 4, 5]


#### Dict

In [ ]:
capitals = {"USA":"Washington D.C.", "France":"Paris", "India":"New Delhi"}
print(capitals)

{'USA': 'Washington D.C.', 'France': 'Paris', 'India': 'New Delhi'}


#### Set

In [ ]:
a = (1,1,1,2,2,2,3,3,3,4,4,4,5,5,5)
b = set(a)
print(b)

{1, 2, 3, 4, 5}


#### Len

In [ ]:
print(len(a))

15


In [ ]:
print(len(capitals))

3


In [ ]:
print(len(b))

5


### Funzioni

In [ ]:
import numpy as np

In [ ]:

def myfunction():
    x = np.random.normal(100)
    return(np.mean(x))

myfunction()

100.14979848964428

In [ ]:
def myfunction2(x):
    return(x + np.random.normal(x))

In [ ]:
myfunction2(100)

199.43511332159784

### Arrays (Vettori)

In [ ]:
firstVector = np.array([1,2,3,4,5])
firstVector

array([1, 2, 3, 4, 5])

In [ ]:
secondVector = np.array(["a", "b","hello"])
secondVector

array(['a', 'b', 'hello'], dtype='<U5')

In [ ]:
firstVector + secondVector

UFuncTypeError: ufunc 'add' did not contain a loop with signature matching types (dtype('<U11'), dtype('<U11')) -> dtype('<U11')

In [ ]:
newVector = np.append(firstVector, secondVector)
newVector

array(['1', '2', '3', '4', '5', 'a', 'b', 'hello'], dtype='<U11')

#### Estrazione di un elemento da un vettore

In [ ]:
newvector = np.array([1,2,3,4,5])
print(newvector)

[1 2 3 4 5]


In [ ]:
esempio1 = newvector[3]
print(esempio1)

4


In [ ]:
esempio2 = newvector[[1,4]]
print(esempio2)

[2 5]


#### Operazioni su vettori

In [ ]:
x = np.array([1,5,10,15,20])
print(x)

[ 1  5 10 15 20]


In [ ]:
x2 = 2 * x
print(x2)

[ 2 10 20 30 40]


In [ ]:
x3 = x**2
print(x3)

[  1  25 100 225 400]


In [ ]:
x4 = x/x2
print(x4)

[0.5 0.5 0.5 0.5 0.5]


In [ ]:
x5 = np.round(x * (x/x2) ** 3.5 + np.sqrt(x4), 4)
print(x5)

[0.7955 1.149  1.591  2.0329 2.4749]


In [ ]:
x6 = np.round(np.append(np.append(x2[1:3], x3[0:1]), x5[3]), 2)
print(x6)

[10.   20.    1.    2.03]


### Altro sui vettori

In [ ]:
x = np.full(10, fill_value=0, dtype = int)
print(x)

[0 0 0 0 0 0 0 0 0 0]


In [ ]:
x = np.full(10, fill_value=0, dtype = float)
print(x)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [ ]:
y = np.full(5, fill_value=False, dtype = bool)
print(y)

[False False False False False]


In [ ]:
isinstance(x, np.ndarray)

True

In [ ]:
p = [1,2,3,4,5]
isinstance(p, np.ndarray)

False

In [ ]:
z = np.append(np.array([1]), np.array(range(7,10)))
print(z)

[1 7 8 9]


In [ ]:
w = np.array(["a", "b", "c"])
print(w)
print(type(w))
w

['a' 'b' 'c']
<class 'numpy.ndarray'>


array(['a', 'b', 'c'], dtype='<U1')

### Explicit coercion

In [ ]:
x = np.array(np.arange(5,11))
x

array([ 5,  6,  7,  8,  9, 10])

In [ ]:
type(x)

numpy.ndarray

In [ ]:
x.astype(int)

array([ 5,  6,  7,  8,  9, 10])

In [ ]:
x.dtype

dtype('int32')

In [ ]:
y = x.astype(float)

In [ ]:
y.dtype

dtype('float64')

In [ ]:
x.astype(bool)

array([ True,  True,  True,  True,  True,  True])

In [ ]:
x.astype(str)

array(['5', '6', '7', '8', '9', '10'], dtype='<U11')

In [ ]:
z = np.array(["a", "b","c"])

In [ ]:
z.astype(bool)

ValueError: invalid literal for int() with base 10: 'a'

### Type conversion

In [ ]:
num_int = 123

In [ ]:
num_flo = 1.23

In [ ]:
num_new = num_int + num_flo
num_new

124.23

In [ ]:
print("datatype of num_int: ", type(num_int))

datatype of num_int:  <class 'int'>


In [ ]:
print("datatype of num_flo: ", type(num_flo))

datatype of num_flo:  <class 'float'>


In [ ]:
print("datatype of num_new: ", type(num_new))

datatype of num_new:  <class 'float'>


In [ ]:
num_str = "456"

In [ ]:
print("Data type of num_str: ", type(num_str))

Data type of num_str:  <class 'str'>


In [ ]:
print(num_int + num_str)

TypeError: unsupported operand type(s) for +: 'int' and 'str'