### Esercizio 1

Scrivere le seguenti formule in Python
Per le funzioni sqrt(), log(), exp(), sin() e cos() importare la libreria Numpy

In [1]:
import numpy as np

Formula 1

$$\left[\frac{7*(2+1) - 2*3}{(1+2)}\right]-[(3*2+5) - 10]$$

In [2]:
((7 * (2 + 1) - 2*3)/(1 + 2)) - ((3 * 2 + 5) - 10)

4.0

Formula 2

$$\frac{x}{\sqrt{ln(|x|)}} $$

                                                            dove x = 5

In [3]:
x = 5
x / (np.sqrt(np.log(abs(x))))

3.941240079466144

Formula 3

$$e^{\sqrt{\frac{1 - x}{x + 2}}}$$

                                                            dove x = 0,5

In [4]:
x = 0.5
np.exp(np.sqrt((1-x)/(x+2)))

1.5639483159353722

Formula 4

$$sin(|x|) + cos(|x|)$$

                                                            dove x = 7

In [5]:
x= 7
np.sin(abs(x)) + np.cos(abs(x))

1.4108888530620938

### Esercizio 2 - Variabili

1 - Creare le variabili A, B, C con valori 3, 2.0, "7"

In [19]:
A = 3
B = 2.0
C = "7"

2 - Verificare il tipo di variabili

In [8]:
print(type(A))
print(type(B))
print(type(C))

<class 'int'>
<class 'float'>
<class 'str'>


In [9]:
print("La variabile A è di tipo: ", type(A))

La variabile A è di tipo:  <class 'int'>


3 - Creare la matrice (array) v1 con queste variabili

In [10]:
v1 = np.array([A, B, C])
print(v1)
print(type(v1))

['3' '2.0' '7']
<class 'numpy.ndarray'>


ricordare che il tipo di parentesi determina il tipo di oggetto

In [11]:
v2 = [A, B, C]
print(v2)
print(type(v2))

[3, 2.0, '7']
<class 'list'>


In [12]:
v3 = (A, B, C)
print(v3)
print(type(v3))

(3, 2.0, '7')
<class 'tuple'>


In [13]:
v4 = ([A, B, C])
print(v4)
print(type(v4))

[3, 2.0, '7']
<class 'list'>


4 - Verificare il tipo di v1

In [14]:
v1.dtype

dtype('<U32')

A data type object (an instance of numpy. dtype class) describes how the bytes in the fixed-size block of memory
corresponding to an array item should be interpreted.
It describes the following aspects of the data: Type of the data (integer, float, Python object, etc.)
The course wants you to see that while the input list contains a float, a string and a boolean, the resulting array just has strings. The float and boolean have converted to their string counterparts. – 
hpaulj


5 - Creare una nuova variabile D come somma di A, B, C

In [20]:
D = A + B + C

TypeError: unsupported operand type(s) for +: 'float' and 'str'

Non è possibile sommare numeri con stringhe. Per creare la variabile richiesta occorre intervenire su C

In [21]:
C = float(C)
D = np.sum([A, B, C])
print(D)

12.0


6 - Creare la matrice v2 con queste variabili

In [23]:
v2 = np.array([A, B, C, D])
print(v2)
print(type(v2))

[ 3.  2.  7. 12.]
<class 'numpy.ndarray'>


7 - Verifica il tipo della matrice v2

In [24]:
v2.dtype

dtype('float64')

8 - Trovare massimo, minimo e media di v2

In [25]:
print(max(v2))
print(min(v2))
print(np.average(v2))

12.0
2.0
6.0


### Esercizio 3 - Operzioni sugli array

1 - Creare il vettore v3 composta dai numeri nell'intervallo 13;25

In [26]:
v3 = np.arange(13,26)
print(v3)

[13 14 15 16 17 18 19 20 21 22 23 24 25]


2 - Calcolare media, quadrato e logaritmo degli elementi di v3

In [27]:
print(np.average(v3))
print(np.power(v3,2))
print(np.log(v3))
print(np.log10(v3))

19.0
[169 196 225 256 289 324 361 400 441 484 529 576 625]
[2.56494936 2.63905733 2.7080502  2.77258872 2.83321334 2.89037176
 2.94443898 2.99573227 3.04452244 3.09104245 3.13549422 3.17805383
 3.21887582]
[1.11394335 1.14612804 1.17609126 1.20411998 1.23044892 1.25527251
 1.2787536  1.30103    1.32221929 1.34242268 1.36172784 1.38021124
 1.39794001]


3 - Eliminare gli elementi in posizione da 3 e 9 dalla matrice v3

In [29]:
v4 = np.delete(v3, [2,8])
print(v4)

[13 14 16 17 18 19 20 22 23 24 25]


4 - Aggiungere il numero 101 all'inizio di v3

In [30]:
v5 = np.append(np.array([101]), v3)
print(v5)

[101  13  14  15  16  17  18  19  20  21  22  23  24  25]


5 - Aggiungere il numero 5 alla fine di v5

In [31]:
v6 = np.append(v5, np.array([5]))
print(v6)

[101  13  14  15  16  17  18  19  20  21  22  23  24  25   5]


6 - Creare una  nuova matrice v7 partendo da v6 con i soli elementi maggiori di 15

In [32]:
v7 = v6[v6 >= 15]
print(v7)

[101  15  16  17  18  19  20  21  22  23  24  25]


7 - Creare una nuova matrice v8 con gli elementi da 16 a 20 compresi della matrice v6

In [33]:
v8 = v6[(v6>=16) & (v6<=20)]
print(v8)

[16 17 18 19 20]


8 - Aggiungere a v6 la somma degli elementi di v8 

In [34]:
v9 = np.sum(v8) + v3
print(v9)

[103 104 105 106 107 108 109 110 111 112 113 114 115]


9 - Estrarre gli elementi di v9 fino alla settima posizione

In [35]:
v10 = v9[:6]
print(v10)

[103 104 105 106 107 108]


In [36]:
v11 = v9[6:]
print(v11)

[109 110 111 112 113 114 115]


10 - Estrarre gli elementi di v9 dalla seconda alla quinta posizione a intervalli di 2

In [37]:
v12 = v9[1:5:2]
print(v12)

[104 106]


In [38]:
v13 = v9[4:10:1]
print(v13)

[107 108 109 110 111 112]


### Esercizio 4 - Matrice con numeri  casuali

1 - Creare una matrice 1x10 composta da valori casuali compresi fra 1 e 5

In [39]:
np.random.seed(1)
a1 = np.random.choice(np.arange(1,5), size = 10)
print(a1)

[2 4 1 1 4 2 4 2 4 1]


2 - Calcolare il prodotto di tutti i valori di a1

In [40]:
# primo modo
a2 = 1

for item in a1:
    a2 = a2 * item
print(a2)

2048


In [41]:
# secondo modo

index = 0
a3 = 1
while index < len(a1):
    a3 = a3 * a1[index]
    index += 1
    
print(a3)

2048


In [42]:
# controllo
print(np.prod(a1))

2048


### Esercizio 5 - File python con all'interno una funzione

1 - Creare uno script chiamato trial_function.py
2 - All'interno del file creare una funzione chiamata myfunction che calcola un po' di statistiche di una matrice passata come input 

In [ ]:
def my_function(x):
	return(sum(x), min(x), max(x), np.average(x), np.std(x))


3 - Creare una matrice 1X20 composta da  numeri interi scelti a caso fra 1 e 100
4 - Chiamare la funzione da Spyder o Jupiter

In [43]:
from trial_function import myfunction
np.random.seed(0)
x = np.random.choice(np.arange(1,100), size = 20)
myfunction(x)

(1186, 10, 89, 59.3, 25.088044961694404)